### ISSUE TITLE
[Flatpak] Files/Common.py:287 fetchImageFromUrl() missing aspectRatio argument

### ISSUE THREAD

**Issue by tinywrkb** [arunsivaramanneo/GPU-Viewer#63]
There's no much to add on top what explained in the title.  
Here's the output messages

```
Traceback (most recent call last):
  File "/app/share/gpu-viewer/Files/VulkanViewer.py", line 977, in radcall
    Devices(text)
  File "/app/share/gpu-viewer/Files/VulkanViewer.py", line 131, in Devices
    distro_logo = getLogo(valueRHS[i])
  File "/app/share/gpu-viewer/Files/Common.py", line 287, in getLogo
    logo_pixbuf = fetchImageFromUrl(const.Flatpak_logo,32,20)
TypeError: fetchImageFromUrl() missing 1 required positional argument: 'aspectRatio'
```

This seems to fix the error
```
diff --git a/Files/Common.py b/Files/Common.py
index f994bca..a31ad23 100644
--- a/Files/Common.py
+++ b/Files/Common.py
@@ -284,7 +284,7 @@ def getLogo(line):
     if "Ubuntu" in line and "Gnome" not in line:
         logo_pixbuf  = fetchImageFromUrl(const.Ubuntu_logo,32,20, True)
     elif "Flatpak" in line:
-        logo_pixbuf = fetchImageFromUrl(const.Flatpak_logo,32,20)
+        logo_pixbuf = fetchImageFromUrl(const.Flatpak_logo,32,20, True)
     elif "Kubuntu" in line:
         logo_pixbuf = fetchImageFromUrl(const.Kubuntu_logo,32,20)
     elif "Lubuntu" in line:
```

And the Flatpak logo is displayed correctly as far as I can tell.
![swappy-20230122-195225](https://user-images.githubusercontent.com/44030034/213931770-548d5cc2-aafb-4272-9780-4d5193e64905.png)

**Comment by arunsivaramanneo** [comment]
Ah crap ... I have missed out for other distro as well :( , no idea why it didn't throw any error on my setup ... I am working on removing the theming dependency i will do more tests and try to do a new Release ... thanks a lot  for letting me know ,...

**Comment by arunsivaramanneo** [comment]
I have fixed the issue and released a new update, Please do check and if all Ok .. close the issue

**Comment by tinywrkb** [comment]
Looks good.
